package com.github.wkw.share.dao;

import com.github.wkw.share.domain.ShareComment;
import com.github.wkw.share.domain.ShareCommentExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ShareCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_comment
     *
     * @mbg.generated
     */
    long countByExample(ShareCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_comment
     *
     * @mbg.generated
     */
    int deleteByExample(ShareCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_comment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_comment
     *
     * @mbg.generated
     */
    int insert(ShareComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_comment
     *
     * @mbg.generated
     */
    int insertSelective(ShareComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShareComment selectOneByExample(ShareCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShareComment selectOneByExampleSelective(@Param("example") ShareCommentExample example, @Param("selective") ShareComment.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ShareComment> selectByExampleSelective(@Param("example") ShareCommentExample example, @Param("selective") ShareComment.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_comment
     *
     * @mbg.generated
     */
    List<ShareComment> selectByExample(ShareCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShareComment selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShareComment.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_comment
     *
     * @mbg.generated
     */
    ShareComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShareComment selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_comment
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShareComment record, @Param("example") ShareCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_comment
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShareComment record, @Param("example") ShareCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShareComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShareComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ShareCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}