package com.github.wkw.share.dao;

import com.github.wkw.share.domain.ShareUser;
import com.github.wkw.share.domain.ShareUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShareUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_user
     *
     * @mbg.generated
     */
    long countByExample(ShareUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_user
     *
     * @mbg.generated
     */
    int deleteByExample(ShareUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_user
     *
     * @mbg.generated
     */
    int insert(ShareUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_user
     *
     * @mbg.generated
     */
    int insertSelective(ShareUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShareUser selectOneByExample(ShareUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShareUser selectOneByExampleSelective(@Param("example") ShareUserExample example, @Param("selective") ShareUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ShareUser> selectByExampleSelective(@Param("example") ShareUserExample example, @Param("selective") ShareUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_user
     *
     * @mbg.generated
     */
    List<ShareUser> selectByExample(ShareUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShareUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShareUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_user
     *
     * @mbg.generated
     */
    ShareUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShareUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShareUser record, @Param("example") ShareUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShareUser record, @Param("example") ShareUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShareUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShareUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ShareUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}