package com.github.wkw.share.dao;

import com.github.wkw.share.domain.ShareFollow;
import com.github.wkw.share.domain.ShareFollowExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShareFollowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_follow
     *
     * @mbg.generated
     */
    long countByExample(ShareFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_follow
     *
     * @mbg.generated
     */
    int deleteByExample(ShareFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_follow
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_follow
     *
     * @mbg.generated
     */
    int insert(ShareFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_follow
     *
     * @mbg.generated
     */
    int insertSelective(ShareFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_follow
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShareFollow selectOneByExample(ShareFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_follow
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShareFollow selectOneByExampleSelective(@Param("example") ShareFollowExample example, @Param("selective") ShareFollow.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_follow
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ShareFollow> selectByExampleSelective(@Param("example") ShareFollowExample example, @Param("selective") ShareFollow.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_follow
     *
     * @mbg.generated
     */
    List<ShareFollow> selectByExample(ShareFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_follow
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShareFollow selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShareFollow.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_follow
     *
     * @mbg.generated
     */
    ShareFollow selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_follow
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShareFollow selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_follow
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShareFollow record, @Param("example") ShareFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_follow
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShareFollow record, @Param("example") ShareFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_follow
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShareFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_follow
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShareFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_follow
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ShareFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_follow
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}