package com.github.wkw.share.dao;

import com.github.wkw.share.domain.ShareCategory;
import com.github.wkw.share.domain.ShareCategoryExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ShareCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_category
     *
     * @mbg.generated
     */
    long countByExample(ShareCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_category
     *
     * @mbg.generated
     */
    int deleteByExample(ShareCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_category
     *
     * @mbg.generated
     */
    int insert(ShareCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_category
     *
     * @mbg.generated
     */
    int insertSelective(ShareCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShareCategory selectOneByExample(ShareCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShareCategory selectOneByExampleSelective(@Param("example") ShareCategoryExample example, @Param("selective") ShareCategory.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ShareCategory> selectByExampleSelective(@Param("example") ShareCategoryExample example, @Param("selective") ShareCategory.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_category
     *
     * @mbg.generated
     */
    List<ShareCategory> selectByExample(ShareCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShareCategory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShareCategory.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_category
     *
     * @mbg.generated
     */
    ShareCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShareCategory selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_category
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShareCategory record, @Param("example") ShareCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_category
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShareCategory record, @Param("example") ShareCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShareCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShareCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ShareCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}