package com.github.wkw.share.dao;

import com.github.wkw.share.domain.ShareLike;
import com.github.wkw.share.domain.ShareLikeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShareLikeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_like
     *
     * @mbg.generated
     */
    long countByExample(ShareLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_like
     *
     * @mbg.generated
     */
    int deleteByExample(ShareLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_like
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_like
     *
     * @mbg.generated
     */
    int insert(ShareLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_like
     *
     * @mbg.generated
     */
    int insertSelective(ShareLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_like
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShareLike selectOneByExample(ShareLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_like
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShareLike selectOneByExampleSelective(@Param("example") ShareLikeExample example, @Param("selective") ShareLike.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_like
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ShareLike> selectByExampleSelective(@Param("example") ShareLikeExample example, @Param("selective") ShareLike.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_like
     *
     * @mbg.generated
     */
    List<ShareLike> selectByExample(ShareLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_like
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShareLike selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShareLike.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_like
     *
     * @mbg.generated
     */
    ShareLike selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_like
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShareLike selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_like
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShareLike record, @Param("example") ShareLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_like
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShareLike record, @Param("example") ShareLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_like
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShareLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_like
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShareLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_like
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ShareLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_like
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}