package com.github.wkw.share.dao;

import com.github.wkw.share.domain.ShareFeed;
import com.github.wkw.share.domain.ShareFeedExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShareFeedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_feed
     *
     * @mbg.generated
     */
    long countByExample(ShareFeedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_feed
     *
     * @mbg.generated
     */
    int deleteByExample(ShareFeedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_feed
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_feed
     *
     * @mbg.generated
     */
    int insert(ShareFeed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_feed
     *
     * @mbg.generated
     */
    int insertSelective(ShareFeed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_feed
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShareFeed selectOneByExample(ShareFeedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_feed
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShareFeed selectOneByExampleSelective(@Param("example") ShareFeedExample example, @Param("selective") ShareFeed.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_feed
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ShareFeed> selectByExampleSelective(@Param("example") ShareFeedExample example, @Param("selective") ShareFeed.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_feed
     *
     * @mbg.generated
     */
    List<ShareFeed> selectByExample(ShareFeedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_feed
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShareFeed selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShareFeed.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_feed
     *
     * @mbg.generated
     */
    ShareFeed selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_feed
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShareFeed selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_feed
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShareFeed record, @Param("example") ShareFeedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_feed
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShareFeed record, @Param("example") ShareFeedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_feed
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShareFeed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_feed
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShareFeed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_feed
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ShareFeedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_feed
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}