package com.github.wkw.share.dao;

import com.github.wkw.share.domain.ShareUserInfo;
import com.github.wkw.share.domain.ShareUserInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShareUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_user_info
     *
     * @mbg.generated
     */
    long countByExample(ShareUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_user_info
     *
     * @mbg.generated
     */
    int deleteByExample(ShareUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_user_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_user_info
     *
     * @mbg.generated
     */
    int insert(ShareUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_user_info
     *
     * @mbg.generated
     */
    int insertSelective(ShareUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_user_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShareUserInfo selectOneByExample(ShareUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_user_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShareUserInfo selectOneByExampleSelective(@Param("example") ShareUserInfoExample example, @Param("selective") ShareUserInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_user_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ShareUserInfo> selectByExampleSelective(@Param("example") ShareUserInfoExample example, @Param("selective") ShareUserInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_user_info
     *
     * @mbg.generated
     */
    List<ShareUserInfo> selectByExample(ShareUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_user_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShareUserInfo selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShareUserInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_user_info
     *
     * @mbg.generated
     */
    ShareUserInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_user_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShareUserInfo selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_user_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShareUserInfo record, @Param("example") ShareUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_user_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShareUserInfo record, @Param("example") ShareUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_user_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShareUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_user_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShareUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_user_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ShareUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_user_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}